name: 01 Setting up Project

on: 
    push:
    workflow_dispatch:

jobs:
    initialise:
        runs-on: ubuntu-latest
        steps:
            name: Checkout Code 
            uses: actions/checkout@v4
            name: Setup Python
            uses: actions/setup-python@3