name: 01 Setting up Project

on:
    workflow_dispatch:

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v5
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: 3.12.x
            - name: Github events
              run: |
                echo "triggered by ${{ github.event_name }}"
                echo "Github actor: ${{ github.actor }}"

                echo "Github SHA: ${{ github.sha }}"
