name: 01 Setting up Project

on:
    workflow_dispatch:

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@3